# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_first_intersections_parallel <- function(centroids, normals, verticesB, facesB, epsilon) {
    .Call(`_doolkit_find_first_intersections_parallel`, centroids, normals, verticesB, facesB, epsilon)
}

find_closest_triangles_parallel <- function(nodesA, facesA, nodesB, facesB) {
    .Call(`_doolkit_find_closest_triangles_parallel`, nodesA, facesA, nodesB, facesB)
}

find_closest_triangles <- function(nodesA, facesA, nodesB, facesB) {
    .Call(`_doolkit_find_closest_triangles`, nodesA, facesA, nodesB, facesB)
}

